### ISSUE TITLE
Bewertung Projekt 7

### ISSUE THREAD

**Issue by Wiredaemon** [ProPra16/programmierpraktikum-abschlussprojekt-cookiejar#2]
Hallo @ProPra16/cookiejar 
Ich habe mir euer Projekt angesehen und muss sagen, es funktioniert sehr schön. Ich habe mir eure Commit history grob durchgesehen und auch den Code. 
Der Code ist nicht durchdokumentiert, aber er ist sehr übersichtlich und die Struktur eurer Arbeit alleine gibt genug Kontext um sich gut durcharbeiten zu können. Sehr gute Arbeit! 

Nur eine Sache muss ich @yasch107 ans Herz legen. 
Deiner Commit History nach hast du leider sehr wenig am Projekt mitgewirkt. Wenn du noch Projekt 7 bestehen möchtest, dann suche dir ein Thema aus und implementiere es bis Donnerstag den 21.7.

Dazu hat auch Jens im Ilias schon was geschrieben. Orientiere dich an diesem Post:

https://ilias.hhu.de/ilias_0500xy/ilias/ilias.php?ref_id=414871&cmdClass=ilobjforumgui&thr_pk=12217&cmd=viewThread&cmdNode=55:pj&baseClass=ilrepositorygui

An @miwer106 und @matthiasmetzen : Ihr habt Projekt 7 erfolgreich bestanden. Glückwunsch!

**Comment by yasch107** [comment]
Hallo,
ich hoffe du hast gesehen, dass ich in einem Branch etwas nachgearbeitet habe, es allerdings nicht ganz funktioniert und ich es deswegen nicht gemerged habe. (Wobei ich nicht weiß, ob nicht funktionierende Teile des Programms überhaupt mit ok bewertet werden können.)
Gruß
Yannick

**Comment by Wiredaemon** [comment]
Hallo @yasch107 
Tut mir leid, das habe ich nicht gesehen.

Habe das ganze jetzt noch einmal mir angesehen aber leider bekomme ich eine javafx.fxml.LoadException und auch wenn ich da einen kleinen fix reinwerfe, so dass das fxml geladen wird bekomme ich eine java.lang.NullPointerException gleich im Anschluss.
Daher ist der Code leider nicht ausreichend, denn das Feature ist leider nicht funktionsfähig.  :/
